image:
    file: Dockerfile
tasks:
  - init: "echo 'export STACK_ROOT=/workspace/mini-grin/.stack' >> ~/.bashrc; source ~/.bashrc; mkdir -p $STACK_ROOT; echo 'local-bin-path: /workspace/mini-grin/.bin' > $STACK_ROOT/config.yaml; stack install"
    command: "echo 'export STACK_ROOT=/workspace/mini-grin/.stack' >> ~/.bashrc; source ~/.bashrc"
